services:
  nginx-traffic:
    image: nginx:latest
    container_name: nginx-traffic
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - python-api-traffic

  mysql-traffic:
    image: mysql:latest
    container_name: mysql-traffic
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: traffic
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  python-api-traffic:
    build: ./api
    container_name: python-api-traffic
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    depends_on:
      - mysql-traffic

  adminer-traffic:
    image: adminer:latest
    container_name: adminer-traffic
    ports:
      - "8080:8080"
    depends_on:
      - mysql-traffic